#!/bin/bash -l

############# SLURM SETTINGS #############
#SBATCH --account=project0005         # account name (mandatory), if the job runs under a project then it'll be the project name, if not then it should =none
#SBATCH --job-name=addcount  # some descriptive job name of your choice
#SBATCH --output=%x-%J.out            # output file name will contain job name  + job ID
#SBATCH --error=%x-%J.err             # error file name will contain job name  + job ID
#SBATCH --time=0-01:00:00             # time limit for the whole run, in the form of d-hh:mm:ss, also accepts mm, mm:ss, hh:mm:ss, d-hh, d-hh:mm
#SBATCH --mem=2G                      # memory required per node, in the form of [num][M|G|T]
#SBATCH --ntasks=1                    # number of Slurm tasks to be launched, increase for multi-process runs ex. MPI
#SBATCH --cpus-per-task=10             # number of processor cores to be assigned for each task, default is 1, increase for multi-threaded runs
#SBATCH --ntasks-per-node=1           # number of tasks to be launched on each allocated node

### Code section

awk '{ $NF = $NF " " (NR * 10000); print }' f1_chr1_mean.txt > f1post_chr1_count.txt

awk '{ $NF = $NF " " (NR * 10000); print }' f1_chr2_mean.txt > f1post_chr2_count.txt

awk '{ $NF = $NF " " (NR * 10000); print }' f1_chr3_mean.txt > f1post_chr3_count.txt

awk '{ $NF = $NF " " (NR * 10000); print }' f1_chr4_mean.txt > f1post_chr4_count.txt

awk '{ $NF = $NF " " (NR * 10000); print }' f1_chr5_mean.txt > f1post_chr5_count.txt

awk '{ $NF = $NF " " (NR * 10000); print }' f1_chrx_mean.txt > f1post_chrx_count.txt
