#!/bin/bash -l

################ SLURM SETTINGS ################
#SBATCH --account=project0005             
#SBATCH --job-name=depth_calc_filter                      
#SBATCH --output=%x-%J.out                
#SBATCH --error=%x-%J.err               
#SBATCH --time=0-1:00:00               
#SBATCH --mem=50G                         
#SBATCH --ntasks=1                        
#SBATCH --cpus-per-task=1                 
#SBATCH --ntasks-per-node=1
#SBATCH --mail-user=p.campbell.5@research.gla.ac.uk
#SBATCH --mail-type=ALL

################ SCRIPT ################

################ FARM1 AVERAGE (FILTERED DATASET)

awk 'NR > 1 {sum += $4} END {if (NR>1) print sum/(NR-1)}' f1post_depth_filtered.txt > f1post_filtered_average.txt

awk 'NR > 1 {sum += $4} END {if (NR>1) print sum/(NR-1)}' f1pre_depth_filtered.txt > f1pre_filtered_average.txt

################ FARM2 AVERAGE (FILTERED DATASET)

awk 'NR > 1 {sum += $4} END {if (NR>1) print sum/(NR-1)}' f2post_depth_filtered.txt > f2post_filtered_average.txt
awk 'NR > 1 {sum += $4} END {if (NR>1) print sum/(NR-1)}' f2pre_depth_filtered.txt > f2pre_filtered_average.txt

################ FARM3 AVERAGE (FILTERED DATASET)

awk 'NR > 1 {sum += $4} END {if (NR>1) print sum/(NR-1)}' f3post_depth_filtered.txt > f3post_filtered_average.txt
awk 'NR > 1 {sum += $4} END {if (NR>1) print sum/(NR-1)}' f3pre_depth_filtered.txt > f3pre_filtered_average.txt
