#!/bin/bash -l

############# SLURM SETTINGS #############
#SBATCH --account=project0005         # account name (mandatory), if the job runs under a project then it'll be the project name, if not then it should =none
#SBATCH --job-name=grenedalff1        # some descriptive job name of your choice
#SBATCH --output=%x-%J.out            # output file name will contain job name  + job ID
#SBATCH --error=%x-%J.err             # error file name will contain job name  + job ID
#SBATCH --time=0-12:00:00             # time limit for the whole run, in the form of d-hh:mm:ss, also accepts mm, mm:ss, hh:mm:ss, d-hh, d-hh:mm
#SBATCH --mem=10G                      # memory required per node, in the form of [num][M|G|T]
#SBATCH --ntasks=1                    # number of Slurm tasks to be launched, increase for multi-process runs ex. MPI
#SBATCH --cpus-per-task=1             # number of processor cores to be assigned for each task, default is 1, increase for multi-threaded runs
#SBATCH --ntasks-per-node=1           # number of tasks to be launched on each allocated node

############# LOADING MODULES #############

module load apps/miniforge
conda activate grenedalf-0.6.2

############# MY CODE #############

# Calculate Fst in 10kb windows along the genome:

grenedalf fst \
--sam-path /mnt/autofs/data/userdata/project0005/for_paul_oster/2.bwasplitter/farm_1_posttx_bwasplitter/farm_1_posttx_bwasplitter_out/farm_1_posttx.merged.sorted.marked.bam \
--sam-path /mnt/autofs/data/userdata/project0005/for_paul_oster/2.bwasplitter/farm_1_pretx_bwasplitter/farm_1_pretx_bwasplitter_out/farm_1_pretx.merged.sorted.marked.bam \
--sam-min-map-qual 40 \
--sam-min-base-qual 30 \
--reference-genome-fasta /users/2320707c/project0005/for_paul_oster/ref_genomes/GCA_964213955.1_nxOstOste4.1_genomic.fna
--filter-sample-min-count 2 \
--filter-sample-min-read-depth 50 \
--filter-sample-max-read-depth 300 \
--window-type interval \
--window-interval-width 100000 \
--window-average-policy valid-loci \
--method unbiased-nei \
--pool-sizes 1000 \
--no-extra-columns \
--separator-char tab \
--file-prefix farm1 \
--threads 24 \
--log-file grenedalf_farm1.log
 
