#!/bin/bash -l

############# SLURM SETTINGS #############
#SBATCH --account=project0005         # account name (mandatory), if the job runs under a project then it'll be the project name, if not then it should =none
#SBATCH --job-name=mean10000  # some descriptive job name of your choice
#SBATCH --output=%x-%J.out            # output file name will contain job name  + job ID
#SBATCH --error=%x-%J.err             # error file name will contain job name  + job ID
#SBATCH --time=0-01:00:00             # time limit for the whole run, in the form of d-hh:mm:ss, also accepts mm, mm:ss, hh:mm:ss, d-hh, d-hh:mm
#SBATCH --mem=5G                      # memory required per node, in the form of [num][M|G|T]
#SBATCH --ntasks=1                    # number of Slurm tasks to be launched, increase for multi-process runs ex. MPI
#SBATCH --cpus-per-task=10             # number of processor cores to be assigned for each task, default is 1, increase for multi-threaded runs
#SBATCH --ntasks-per-node=1           # number of tasks to be launched on each allocated node

### Code section

awk '{ sum += $3; count++; if (count == 10000) { print sum / count; sum = 0; count = 0 } } END { if (count > 0) print sum / count }' f1chr1.txt > f1_chr1_mean.txt

awk '{ sum += $3; count++; if (count == 10000) { print sum / count; sum = 0; count = 0 } } END { if (count > 0) print sum / count }' f1chr2.txt > f1_chr2_mean.txt

awk '{ sum += $3; count++; if (count == 10000) { print sum / count; sum = 0; count = 0 } } END { if (count > 0) print sum / count }' f1chr3.txt > f1_chr3_mean.txt

awk '{ sum += $3; count++; if (count == 10000) { print sum / count; sum = 0; count = 0 } } END { if (count > 0) print sum / count }' f1chr4.txt > f1_chr4_mean.txt

awk '{ sum += $3; count++; if (count == 10000) { print sum / count; sum = 0; count = 0 } } END { if (count > 0) print sum / count }' f1chr5.txt > f1_chr5_mean.txt

awk '{ sum += $3; count++; if (count == 10000) { print sum / count; sum = 0; count = 0 } } END { if (count > 0) print sum / count }' f1chrx.txt > f1_chrx_mean.txt




