#!/bin/bash -l

############# SLURM SETTINGS #############
#SBATCH --account=project0005   # account name (mandatory), if the job runs under a project then it'll be the project name, if not then it should =none
#SBATCH --job-name=bwa_4_stats_farm_3_posttx        # some descriptive job name of your choice
#SBATCH --output=%x-%J.out      # output file name will contain job name + job ID
#SBATCH --error=%x-%J.err       # error file name will contain job name + job ID
#SBATCH --time=4-10:00:00       # time limit for the whole run, in the form of d-hh:mm:ss, also accepts mm, mm:ss, hh:mm:ss, d-hh, d-hh:mm
#SBATCH --mem=10G                # memory required per node, in the form of [num][M|G|T]
#SBATCH --ntasks=1              # number of Slurm tasks to be launched, increase for multi-process runs ex. MPI
#SBATCH --cpus-per-task=1       # number of processor cores to be assigned for each task, default is 1, increase for multi-threaded runs
#SBATCH --ntasks-per-node=1     # number of tasks to be launched on each allocated node

############# LOADING MODULES (optional) #############
#module load apps/xxx
#module load libs/xxx

module load apps/miniforge
conda activate bwa_splitter

############# MY CODE #############
# mark duplicates, generate stats, and finalise

sample_name=farm_3_posttx    


ulimit -Sn > snlimit.txt # This will show you the number of jobs you have access to as a check

java -Xmx8g -jar /users/2320707c/project0005/conda/envs/bwa_splitter/share/picard-2.5.0-2/picard.jar MarkDuplicates INPUT=tmp.merged.sorted.bam OUTPUT=tmp.merged.sorted.marked.bam METRICS_FILE=tmp.merged.sorted.marked.metrics TMP_DIR=/users/2320707c/project0005/for_paul_oster/2.bwasplitter/farm_3_posttx_bwasplitter/farm_3_posttx_bwasplitter_out/tmp
/users/2320707c/project0005/conda/envs/bwa_splitter/bin/samtools flagstat tmp.merged.sorted.marked.bam > ${sample_name}.merged.sorted.marked.flagstat
/users/2320707c/project0005/conda/envs/bwa_splitter/bin/samtools stats tmp.merged.sorted.marked.bam | grep ^SN | cut -f 2- > ${sample_name}.merged.sorted.marked.stats
/users/2320707c/project0005/conda/envs/bwa_splitter/bin/bamtools stats -in tmp.merged.sorted.marked.bam > ${sample_name}.merged.sorted.marked.bamstats
/users/2320707c/project0005/conda/envs/bwa_splitter/bin/samtools view --threads 4 -F 12 -b tmp.merged.sorted.marked.bam -o ${sample_name}.merged.sorted.marked.bam
/users/2320707c/project0005/conda/envs/bwa_splitter/bin/samtools view --threads 4 -f 12 tmp.merged.sorted.marked.bam -o ${sample_name}.unmapped.bam
/users/2320707c/project0005/conda/envs/bwa_splitter/bin/samtools index -b ${sample_name}.merged.sorted.marked.bam
#rm R[12]_*
#rm *.tmp.*
#mv *.[eo] logfiles/
touch step4_stats_FINISHED
touch bam_splitter_COMPLETE
